### ISSUE TITLE
Silhouette Score Issue

### ISSUE THREAD

**Issue by emilanz** [crew102/validclust#4]
Hi, 

Am trying to use ValidClust to check for best number of clusters however am getting this error message.

ValueError: The precomputed distance matrix contains non-zero elements on the diagonal. Use np.fill_diagonal(X, 0).

any help?

**Comment by crew102** [comment]
Can you provide a reproducible example of the error you're getting?

**Comment by emilanz** [comment]
Ok here's the code for a randomly generated pandas dataframe which gives the same error message:

import random
import numpy as np
import validclust
from validclust.validclust import ValidClust
df = pd.DataFrame(2 + 3 * np.random.randn(1000, 43))
vclust = ValidClust(k=20, methods=['kmeans'])
tests = vclust.fit_predict(df)
print(tests)

**Comment by crew102** [comment]
Oh yeah, looks like the pairwise distances that you get have some non-zero entries along the diagonal. I'll fix this and publish a new version of the package.

**Comment by emilanz** [comment]
thanks a lot

**Comment by crew102** [comment]
Hey @emilanz , this issue should be fixed now. I'm gonna publish a new version of the package on py-pi soon too, so you may want to just wait until the package is available then with the fix. Otherwise, you can install the development version using the instructions in the readme.
